version: "3"
services:
  redis:
    image: redis
    container_name: redis-instance
    volumes:
      - redis-data:/data

  front-end:
    image: visitor-counter
    ports:
      - 5000:5000

volumes:
  redis-data:
    driver: local
