version: "3"

services:
  product-api:
    container_name: product-api-backend
    image: ashabtariq12/product-api:latest
    restart: always
    environment:
      MONGO_URI: mongodb://mongo:27017/
    ports:
      - 5000:5000
    networks:
      - api-net

  mongodb:
    container_name: product-api-db
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - api-net

volumes:
  mongodb_data:
    driver: local

networks:
  api-net:
    driver: bridge
